package br.unibh.sdm.backend_cliente.entidades;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "cliente")
public class Cliente {

  private String nome;
  private String telefone;
  private String email;
  private String userId;
  private String cpf;

  public Cliente() {
    super();
  }

  public Cliente(String nome, String telefone, String email, String cpf) {
    super();
    this.nome = nome;
    this.telefone = telefone;
    this.email = email;
    this.cpf = cpf;
  }

  @DynamoDBAttribute
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  @DynamoDBAttribute
  public String getTelefone() {
    return telefone;
  }

  public void setTelefone(String telefone) {
    this.telefone = telefone;
  }

  @DynamoDBAttribute
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  @DynamoDBAttribute
  public String getCpf() {
    return cpf;
  }

  public void setCpf(String cpf) {
    this.cpf = cpf;
  }

  @Override
  public String toString() {
    return "Cliente [nome=" + nome + ", telefone=" + telefone + ", email=" + email + ", userId="
        + userId + ", cpf= " + cpf + "]";
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((nome == null) ? 0 : nome.hashCode());
    result = prime * result + ((telefone == null) ? 0 : telefone.hashCode());
    result = prime * result + ((cpf == null) ? 0 : cpf.hashCode());
    result = prime * result + ((userId == null) ? 0 : userId.hashCode());
    result = prime * result + ((email == null) ? 0 : email.hashCode());
    return result;
  }
}